In [ ]:
import gymnasium as gym
import numpy as np

In [ ]:
# Create FrozenLake environment
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=True).unwrapped

In [ ]:
# Number of states and actions
n_states = env.observation_space.n
n_actions = env.action_space.n

In [ ]:
# Parameters
gamma = 0.97
theta = 1e-9

In [ ]:
# Random policy: each action has equal probability
policy = np.ones((n_states, n_actions)) / n_actions

In [ ]:

# Initialize value function
V = np.zeros(n_states)

# -------------------------------------------------
# Policy Evaluation Function
# -------------------------------------------------

def policy_evaluation(env, policy, gamma,theta):
    """
    Performs iterative policy evaluation using the Bellman expectation equation.

    Parameters:
        env    : Gymnasium FrozenLake environment
        policy : Fixed policy to be evaluated
        gamma  : Discount factor
        theta  : Convergence threshold

    Returns:
        V         : Estimated state-value function
        iteration : Number of iterations used for convergence
    """

    n_states=env.observation_space.n

    V=np.zeros(n_states)

    iteration=0

    while True:
        delta=0
        for s in range(n_states):
            v=V[s]
            new_value=0
            for a,action_prob in enumerate(policy[s]):


                for prob,next_state,reward,done in env.P[s][a]:
                    new_value+=action_prob*prob*(
                        reward+gamma*V[next_state]
                    )
            V[s]=new_value


            delta=max(delta,abs(v-V[s]))
            iteration+=1


        if delta<theta:
            break

    return V,iteration


In [ ]:

V, iterations = policy_evaluation(env, policy, gamma, theta)

print("Name:Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("Number of iterations:", iterations)
print("\nState-Value Function:")
print(V)

print("Name: Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("\nState-Value Function as 4x4 Grid:")
print(np.round(V.reshape(4, 4), 4))

env.close()

Name:Payyavula Jeshwanth Kumar
Register Number: 212223240114
Number of iterations: 912

State-Value Function:
[0.0097647  0.00842947 0.01656654 0.00780075 0.01230793 0.
 0.03551887 0.         0.02868173 0.07728551 0.12990301 0.
 0.         0.1601184  0.42287814 0.        ]
Name: Payyavula Jeshwanth Kumar
Register Number: 212223240114

State-Value Function as 4x4 Grid:
[[0.0098 0.0084 0.0166 0.0078]
 [0.0123 0.     0.0355 0.    ]
 [0.0287 0.0773 0.1299 0.    ]
 [0.     0.1601 0.4229 0.    ]]


In [ ]:
print("Slippery:")
env = gym.make("FrozenLake-v1", is_slippery=True).unwrapped
print(env.P[0][2])

print("\nNot Slippery:")
env = gym.make("FrozenLake-v1", is_slippery=False).unwrapped
print(env.P[0][2])

Slippery:
[(0.33333333333333337, 4, 0, False), (0.3333333333333333, 1, 0, False), (0.33333333333333337, 0, 0, False)]

Not Slippery:
[(1.0, 1, 0, False)]


In [ ]:
# Create FrozenLake environment
envf = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False).unwrapped

In [ ]:

# Initialize value function


# -------------------------------------------------
# Policy Evaluation Function
# -------------------------------------------------

def policy_evaluation(envf, policy, gamma,theta):
    """
    Performs iterative policy evaluation using the Bellman expectation equation.

    Parameters:
        env    : Gymnasium FrozenLake environment
        policy : Fixed policy to be evaluated
        gamma  : Discount factor
        theta  : Convergence threshold

    Returns:
        V         : Estimated state-value function
        iteration : Number of iterations used for convergence
    """

    n_states=envf.observation_space.n

    Vf=np.zeros(n_states)

    iterationf=0

    while True:
        delta=0
        for s in range(n_states):
            v=Vf[s]
            new_value=0
            for a,action_prob in enumerate(policy[s]):


                for prob,next_state,reward,done in envf.P[s][a]:
                    new_value+=action_prob*prob*(
                        reward+gamma*Vf[next_state]
                    )
            Vf[s]=new_value


            delta=max(delta,abs(v-Vf[s]))
            iterationf+=1


        if delta<theta:
            break

    return Vf,iterationf


In [ ]:
Vf, iterationf = policy_evaluation(envf, policy, gamma, theta)
print("false")
print("Name:Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("Number of iterations:", iterationf)
print("\nState-Value Function:")
print(Vf)

print("Name: Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("\nState-Value Function as 4x4 Grid:")
print(np.round(Vf.reshape(4, 4), 4))

envf.close()

false
Name:Payyavula Jeshwanth Kumar
Register Number: 212223240114
Number of iterations: 912

State-Value Function:
[0.0097647  0.00842947 0.01656654 0.00780075 0.01230793 0.
 0.03551887 0.         0.02868173 0.07728551 0.12990301 0.
 0.         0.1601184  0.42287814 0.        ]
Name: Payyavula Jeshwanth Kumar
Register Number: 212223240114

State-Value Function as 4x4 Grid:
[[0.0098 0.0084 0.0166 0.0078]
 [0.0123 0.     0.0355 0.    ]
 [0.0287 0.0773 0.1299 0.    ]
 [0.     0.1601 0.4229 0.    ]]


In [ ]:
V, iterations = policy_evaluation(env, policy, gamma, theta)
print("True")
print("Name:Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("Number of iterations:", iterations)
print("\nState-Value Function:")
print(V)

print("Name: Payyavula Jeshwanth Kumar")
print("Register Number: 212223240114")
print("\nState-Value Function as 4x4 Grid:")
print(np.round(V.reshape(4, 4), 4))

env.close()

True
Name:Payyavula Jeshwanth Kumar
Register Number: 212223240114
Number of iterations: 57

State-Value Function:
[0.0097647  0.00842947 0.01656654 0.00780075 0.01230793 0.
 0.03551887 0.         0.02868173 0.07728551 0.12990301 0.
 0.         0.1601184  0.42287814 0.        ]
Name: Payyavula Jeshwanth Kumar
Register Number: 212223240114

State-Value Function as 4x4 Grid:
[[0.0098 0.0084 0.0166 0.0078]
 [0.0123 0.     0.0355 0.    ]
 [0.0287 0.0773 0.1299 0.    ]
 [0.     0.1601 0.4229 0.    ]]
